{% set name = "ipycanvas" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/63/3b/2aa03a35b8f02f750af3092988ad927f887c3a41e018504c0fc13ac93bc8/ipycanvas-{{ version }}.tar.gz
  sha256: 921f1482258b5929b599317b5c129931d80e16be35fa38300a32e7aa4cfe9f89

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - yarn
    - jupyterlab =4
    - hatchling
    - hatch-jupyter-builder
  run:
    - ipywidgets >=7.6.0,<9
    - numpy
    - pillow >=6.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipycanvas
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipycanvas/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipycanvas/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/ipycanvas/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipycanvas\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipycanvas\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\ipycanvas\\package.json (exit 1)          # [win]

about:
  home: http://github.com/martinRenou/ipycanvas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Interactive widgets library exposing the browser's Canvas API
  doc_url: https://ipycanvas.readthedocs.io
  dev_url: http://github.com/martinRenou/ipycanvas

extra:
  recipe-maintainers:
    - martinRenou
