{% set name = "ipycanvas" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9c3940681bc38383390f8c46ea5d8445d6e11c6da6484c37d89df5ae1dac131

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - jupyter-packaging =0.7
    - jupyterlab =3
  run:
    - ipywidgets >=7.6.0,<9
    - numpy
    - pillow >=6.0
    - python >=3.6

test:
  imports:
    - ipycanvas
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipycanvas/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipycanvas/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/ipycanvas/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipycanvas\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipycanvas\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\ipycanvas\\package.json (exit 1)          # [win]

about:
  home: http://github.com/martinRenou/ipycanvas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Interactive widgets library exposing the browser's Canvas API
  doc_url: https://ipycanvas.readthedocs.io
  dev_url: http://github.com/martinRenou/ipycanvas

extra:
  recipe-maintainers:
    - martinRenou
