{% set name = "ipycanvas" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9edc21cdce9d6c0ac45980de1d9b211d9959e34c727c75b52442ec892b2d417

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - nodejs
  run:
    - ipywidgets >=7.5.0
    - numpy
    - pillow >=6.0
    - python >=3.5

test:
  imports:
    - ipycanvas

about:
  home: http://github.com/martinRenou/ipycanvas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "Interactive widgets library exposing the browser's Canvas API"

  dev_url: http://github.com/martinRenou/ipycanvas

extra:
  recipe-maintainers:
    - martinRenou
