{% set name = "ipycanvas" %}
{% set version = "0.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e867c509b01f5c4cfc009f7d921e32e5a12a029ac856e78c04ff15b65692c4a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - yarn
    - jupyterlab =4
    - hatchling
    - hatch-jupyter-builder
  run:
    - ipywidgets >=7.6.0,<9
    - numpy
    - pillow >=6.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipycanvas
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipycanvas/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipycanvas/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/ipycanvas/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipycanvas\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\ipycanvas\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\ipycanvas\\package.json (exit 1)          # [win]

about:
  home: http://github.com/martinRenou/ipycanvas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Interactive widgets library exposing the browser's Canvas API
  doc_url: https://ipycanvas.readthedocs.io
  dev_url: http://github.com/martinRenou/ipycanvas

extra:
  recipe-maintainers:
    - martinRenou
