{% set name = "ipycanvas" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipycanvas/ipycanvas-0.8.1.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b39f2227e806c859f9d702a8b0281135aed99ef496a2090ef795445199276290

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - nodejs
    - jupyter-packaging
    - jupyterlab >=3,<4
  run:
    - ipywidgets >=7.6.0
    - numpy
    - pillow >=6.0
    - python >=3.6
    - orjson

test:
  imports:
    - ipycanvas
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipycanvas/extension.js                                       # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/ipycanvas/index.js                                           # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/ipycanvas/package.json                                      # [unix]
    - if exist %PREFIX%\\share\\jupyter\\nbextensions\\ipycanvas\\extension.js (exit 0) else (exit 1)           # [win]
    - if exist %PREFIX%\\share\\jupyter\\nbextensions\\ipycanvas\\index.js (exit 0) else (exit 1)               # [win]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\ipycanvas\\package.json (exit 0) else (exit 1)          # [win]

about:
  home: http://github.com/martinRenou/ipycanvas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Interactive widgets library exposing the browser's Canvas API
  doc_url: https://ipycanvas.readthedocs.io
  dev_url: http://github.com/martinRenou/ipycanvas

extra:
  recipe-maintainers:
    - martinRenou
