travis:
  secure:
    BINSTAR_TOKEN: VGsJ8UnyJWEwcicQapBsaPfBks8njSt8mZa/aXu9HW9r3ztgWWH4dx90/HcAKkfkC4Bjuo4XlE8rhOFmGmibuO4YKSxR/gBLoGxet/7PI+fmV7Qrdbkw0a6kSJqOk1eMdhOcPh2ScPAyAmbdVkEx/8u/rMn0ePZQQ5m/Eu5Qt0XE7GHZrqsHS7r7XpGHbvD0B/sHMxLO01Xb4G8CunxKde9JLyK2w3wyQFj7GBbSMq190klFlVhAA4BTOFSiFfd4L1nuyPztyAwkaCS48LVRrmtQfpYJqpfDRCjRV0l6fA1hh5rJ/LXlzIAc5mkQTmNSS3ybamuO9/8zgShMI2IuhzDFS5tVmVN09ukWFj0+jpMiMy9kW2BWX3r024u1vtWByu+HE8E0adPGLjTmlpCvj7LVAWfjGQWDaz7TTJen2/DZPYnC5bo6NiwDDLv18gUkWmLDq90fAqsXr8CrOjGlzEHjF+kPzZHsGKQro8k4vYWdFMRSgc/wJiWH2KiEe0gpjJQhAEwxhAgX2Limh84WY/qWKlH6s/a+YO6NhNHI1M/Wj5l/nS6fZP+hCNoQ9N5nU9YcJNNkhxp25I5sMavAtaF3Jg5E2pTp6sKQG++0JluJdDGLde10b0NoPlw+9ukZOne825ipdf8E/pmkMUY35LgZ6dwzWgFr9WXEOCgRqP4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
